cmd/feed-ingress/main.go
ingress/controller.go
ingress/controller_test.go
ingress/loadbalancer.go
k8s/client.go
k8s/client_test.go
k8s/types.go

This PR adds real retrieval of ingresses from the apiserver. It also wires it up into the `feed-ingress` binary.
Also adds some new flags:
```
$ feed-ingress -h                                                                                        (k8s-client) 
Usage of feed-ingress:
-apiserver string
Kubernetes API server URL (default "https://10.254.0.1:443")
-cacertfile string
file containing kubernetes ca certificate (default "/run/secrets/kubernetes.io/serviceaccount/ca.crt")
-debug
enable debug logging
-tokenfile string
file containing kubernetes client authentication token (default "/run/secrets/kubernetes.io/serviceaccount/token")
```
Debug was added for some low level messages I added to check things were working against a real apiserver.

Add retrieval of ingresses from k8s apiserver

---

Makefile
cmd/feed-ingress/main.go
ingress/controller.go
ingress/controller_test.go
k8s/client.go
k8s/client_test.go

The logic tries its best to stay connected while watching. It does this by retrying the connection to the apiserver if it gets disconnected.
The watcher also now sends an update on any successful connect, to ensure the controller will not miss updates from reconnects.

Add watching of ingresses

---

cmd/feed-ingress/main.go
ingress/controller.go
ingress/controller_test.go
ingress/loadbalancer_test.go
ingress/nginx.go
k8s/client.go

Adds /health and /debug/pprof.
Also:
- Properly os.Exit(-1) if the controller has an error
- Controller controls load balancer lifecycle start
- Make controller start/stop safe, and validate controller state

Add health port to ingress controller

---

.travis.yml
Makefile
cmd/feed-ingress/main.go
docker/Dockerfile

Also change it to only release on master builds. To limit number of
images we have (I don't think we need branch builds? We can always push
it locally if we really need it).
And change default ingress port to 8080 so we don't need super user rights
to start up nginx. Needed so we can run as nginx in the Dockerfile.

Use nginx user and move release into Makefile

---

ingress/controller.go
ingress/fake_graceful_nginx.py
ingress/nginx.go

So we know what version is running in our clusters (for security
updates, and things).

Print nginx version on startup

---

ingress/controller.go
ingress/controller_test.go
ingress/nginx/nginx_test.go

Fix unkeyed literals

---

cmd/feed-ingress/main.go
ingress/nginx/nginx.go
ingress/nginx/nginx.tmpl
ingress/nginx/nginx_test.go

This is necessary in Kubernetes so we can specify skydns, since the pod
will be running on host networking.

Add ability to specify dns resolver

---

Makefile

This is necessary since some of the vet checks require that the packages
are installed first.

Change `vet` to depend on `build`

---

ingress/controller.go
ingress/controller_test.go

The ingress resource is namespaced to the service. Since nginx runs in
kube-system, we need the namespace appended to the service name so it can
resolve the service ip.

Include ingress namespace on service backend

---

cmd/feed-ingress/main.go
ingress/nginx/nginx.go
ingress/nginx/nginx.tmpl
ingress/nginx/nginx_test.go

This makes various things configurable now:
- keep alive
- worker connections
- status port
- nginx binary
Also comment nginx.tmpl with what each option does.
Put the /health endpoint on a separate port, so we can restrict access
with external firewall rules. I feel this is simpler than having it
share the ingress port and doing the filtering inside of nginx.
Add /status which uses nginx's stub_status module to give some basic
stats. It would be nicer to use nginx-module-vts, which is far more
detailed (gives stats per service backend), but that requires building
nginx from scratch - and should probably be done separately, if at all.

Improve nginx.tmpl with production like settings

---

cmd/feed-ingress/main.go
ingress/api/lb_entry.go
ingress/controller.go
ingress/controller_test.go
ingress/nginx/nginx.go
ingress/nginx/nginx.tmpl
ingress/nginx/nginx_test.go

Deny everything but localhost by default.
Add support for `sky.uk/allow` annotation on ingress resources.
Add support for a default allow range on ingress, to support blanket
internal access.

Restrict ingress access

---

ingress/controller.go
ingress/controller_test.go
ingress/nginx/nginx.go
ingress/nginx/nginx.tmpl
ingress/nginx/nginx_test.go
ingress/types/lb_entry.go

So we can easily find the ingress in kubernetes that generated the
entry.
This also changes it to sort by name so our config order should remain
relatively stable (not be reordered whenever there is a new or changed
ingress).

Add ingress names to the nginx.conf

---

Dockerfile
cmd/feed-ingress/main.go
ingress/nginx/nginx.go
ingress/nginx/nginx.tmpl
ingress/nginx/nginx_test.go

Using `info` also revealed that the container is unable to set file
limits. This is handled by the docker service, so I've removed the
setting.

Make nginx log level configurable

---

nginx/nginx.tmpl

Until we can prove we need it, let's just remove it. Otherwise it has
unbounded growth.

Remove nginx access log

---

nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

E.g. if someone hits `sky.com/commerce/verification-app/private/ready` it will
proxy to `verification-app/private/ready`, stripping the prefix.
Also fix the location to always have trailing slashes (otherwise it
doesn't work with path prefixes).

Strip the ingress path prefix

---

cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
nginx/nginx.tmpl
nginx/nginx_test.go

Also add support for comma delimited allows, which is necessary now that
we can't combine with a default allow (such as for external access
combined with internal).

Allow annotation replaces default nginx allow

---

cmd/feed-dns/main.go
cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go
k8s/client.go
nginx/nginx.go
util/cmd/cmd.go

Use a periodic logger to check health. Otherwise our log gets spammed
when unhealthy by external calls to the health check endpoint (5s in
kubernetes).

Improve health logging so it doesn't spam

---

cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

It was broken if allow annotation isn't specified. This change fixes
that. Basically, it was doing a split on an empty string, which produces
[]string{""}. This causes an `allow  ;` entry in nginx since it was
simply expanding the slice with `range`.
It also moves default allow into the controller, since everything that
gets an ingress entry should see the default allow as well. It's not
nginx specific.

Fix broken nginx.conf if no allow annotation

---

cmd/feed-ingress/main.go
controller/controller.go
controller/ingress_entry.go
k8s/client.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Brings new config:
- Backend keepalive number and keepalive times
And based on internal production nginx:
- Fix nginx keepalive_requests for client requests
- Disable buffering for use with ELB http listeners

Add upstreams for persistent backend connections

---

elb/elb.go
nginx/nginx.go
nginx/nginx_metrics.go
nginx/nginx_test.go
util/constants.go

Add to `/metrics`:
feed_ingress_nginx_connections
feed_ingress_nginx_connections_reading
feed_ingress_nginx_connections_waiting
feed_ingress_nginx_connections_writing
feed_ingress_nginx_accepts
feed_ingress_nginx_handled
feed_ingress_nginx_requests

Add nginx prometheus metrics

---

cmd/feed-ingress/main.go
controller/controller.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Add flag `-nginx-trusted-frontends`, used by nginx to determine the
client ip for allow/deny directives.

Add trusted frontends for determining client ip

---

Dockerfile
nginx/fake_nginx_failing_reload.sh
nginx/nginx.go
nginx/nginx_test.go
util/cmd/cmd.go

This notifies us if something goes wrong with nginx.conf, which has come
up several times in testing.
If nginx.conf is invalid, it will cause `feed-ingress` to become
unhealthy.

Unhealthy if nginx configuration fails to load

---

cmd/feed-ingress/main.go
controller/updater.go
util/cmd/cmd.go

So we can alert when the ingress controller is unhealthy.
Adds `feed_ingress_unhealthy_time` which is the amount of time in
seconds it has been unhealthy for.
This depends on #57

Track unhealthy time in `/metrics`

---

dns/dns_updater.go
dns/dns_updater_test.go
dns/r53/client.go
dns/r53/client_test.go
invalid-host-ingress.yml

This also starts to add tests for the R53 Client.
The logs are a little verbose atm I'll cut them down before I finish working in this area.

Filter out ingress updates that have an invalid hostname

---

Dockerfile_dns

This is required to hit https endpoints from within the container

Install ca-certificates in dns image

---

cmd/feed-dns/main.go

Was feed_ingress_unhealthy_time, this changes it to
feed_dns_unhealthy_time.

Fix feed-dns healthy metric name

---

util/cmd/cmd.go

Add a very simple 200 endpoint for external liveness probes to make sure
the container is running.

Add /alive endpoint for liveness probes

---

dns/dns_metrics.go
dns/dns_updater.go
dns/dns_updater_test.go
nginx/nginx_test.go

This was failing when it his the aws api.
I also broke up calculateChanges into several smaller methods, to better
understand what the code is doing.
I also changed "invalid_entries" to "skipped_entries", since we'll
likely have a few things outside of the hosted zone (such as jenkins).
This makes it more explicit that such entries aren't invalid, just
skipped by the dns controller since they are outside of its hosted zone.

Don't send duplicate route53 records

---

cmd/feed-ingress/main.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Allows configuration of `server_names_hash_bucket_size` and
`server_names_hash_max_size`
Closes https://github.com/sky-uk/umc-core/issues/1191

Add nginx configuration for server_names_hash_*

---

Dockerfile_dns
Dockerfile_ingress

To resolve problems caused by apt's local cache not matching upstream

Add apt-get clean before doing an update.

---

nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Combine ingress entries with the same host into a single nginx server
directive with multiple locations.
This is required by nginx.

Make nginx server_names unique

---

nginx/nginx.go
nginx/nginx_test.go

nginx will not load the config if we duplicate locations within a single
server block. This change detects that and skips the duplicate location.

Skip duplicate host/paths

---

nginx/nginx.tmpl
nginx/nginx_test.go

To avoid massive duplication in every single Location.
Also add missing X-Forwarded-* as used by jetty, tomcat, and other
connectors.

Move proxy settings into http top level

---

cmd/feed-ingress/main.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Add `-nginx-proxy-protocol` which turns on TCP PROXY protocol for the
nginx listeners.

Support PROXY protocol

---

nginx/nginx.tmpl
nginx/nginx_test.go

This is required for any request that uploads a file via ingress e.g. a docker
registry

Disable payload limits

---

nginx/nginx.tmpl

So proxied servers that do not honour the `X-Forwarded-Host` header, can use the `Host` request header when sending 302 redirects.
Fixes sky-uk/umc-core#1739

Pass Host header to proxied server

---

Dockerfile_ingress
Makefile
build-nginx.sh
cmd/feed-ingress/main.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

For more detailed monitoring per upstream and virtual host.
This is now on /status, and stub_status is moved to /basic_status.
Also added ability to specify the proxy connect timeout, via
-nginx-backend-connect-timeout-seconds.

Add vhost_traffic_status module, connect timeout

---

cmd/feed-ingress/main.go
examples/pod.yml
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

- Enable access logs when "access-log" command line arg is provided.
- Access logs will be written by default in /var/log/nginx/access.log. The target directory can be overriden via command line arg "access-log-dir"
- Access logs use a custom format to capture various time values between
nginx and upstream servers
- Access logs are buffered and flushed every minute unless buffer is full

Toggle access logs via command line argument

---

cmd/feed-ingress/main.go
controller/updater.go
nginx/blocking_nginx.sh
nginx/nginx.go
nginx/nginx_test.go

If many updates came in in a short space of time nginx spawns
many workers processes resulting in OOM kills

Basic throttling for nginx updates

---

cmd/feed-ingress/main.go
elb/elb.go
elb/elb_test.go
nginx/nginx.go
nginx/nginx_test.go

Otherwise ingress can be unavailble for up to 30s

Synchronously update nginx for the first update

---

scripts/logrotate.config

If multiple log files are found e.g. error.log the postrotate will be
executed multiple times witout this

Add shared scripts for nginx log rotation

---

cmd/feed-ingress/main.go

Don't use the client keepalive, instead use what is specified on the
command line.

Fix backend keepalive seconds

---

cmd/feed-ingress/main.go
util/cmd/csv.go
util/cmd/csv_test.go

This will be needed for the feed-dns change as well which is currently
pending.
Missed the usual problem of "".Split(",") producing {""}.

Fix ALB flag if it's empty

---

Dockerfile_ingress

Increase kill timeout in phusion baseimage's /sbin/my_init script.
It defaults to 5 seconds which is not enough time.

Let feed shutdown gracefully

---

dns/dns_updater.go
dns/dns_updater_test.go

Use the ELB/ALB hostedZoneID for alias records, not the managed domain's
zone id.
This was a regression from the ALB changes.

Fix feed-dns updates

---

alb/alb.go
alb/alb_test.go
cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go

- Wait for deregistration delay after sending deregister request, to
ensure connections are drained off in the ALB before stopping nginx.
- Controller stops updaters in reverse order, so ALB is detached before
nginx is stopped.

Deregister from ALB target groups gracefully

---

nginx/nginx.tmpl

To prevent spam when using an error log level of 'error'.

Don't log 404s on error level

---

nginx/nginx.go

There have recently been many problems around getting 502's and 504's partly
caused by nginx reloading. Nginx has also been noticed to reload far more
frequently than expected (10-20 times an hour) and it is very difficult to
investigate the cause of the reload without this log.
Closes https://github.com/sky-uk/umc-core/issues/2672

Log nginx diff at info level.

---

nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

We were reloading almost always due to not sorting the ingress names in
the server comments.

Fix erroneous reloads due to unsorted map data

---

controller/controller.go
controller/ingress_entry.go
nginx/nginx.go
nginx/nginx_test.go

Keep the most recent ingress when duplicate ingresses found to make the order
deterministic, so that new feed deployment or reload always keep the same
ingress when duplicates are found.
The inconsistent ordering originates from`Client#GetIngresses` which returns ingresses in a different order even when they do not change. 
Fix sky-uk/umc-core#2764

Deterministic ordering for duplicate ingresses

---

dns/dns_updater.go
dns/dns_updater_test.go

Send route53 changerecordset requests when hostname or ELB change.
This was done to avoid issuing route53 requests update when they are no changes, as these may fail.
Also append a "." to the alb dns name in all cases for consistency.

Update route53 recordsets only when necessary

---

Makefile

To make it easier to test a change before releasing by allowing to specify build version / target
respository to use

Accept env variables to define version and repo

---

cmd/feed-ingress/main.go
elb/elb.go
elb/elb_test.go

So feed-ingress deployment is non-disruptive when attached to an ELB.

Wait for drain duration on ELB detach

---

CHANGELOG.md
nginx/fake_failing_nginx.sh
nginx/fake_graceful_nginx.py
nginx/nginx.go
nginx/nginx_test.go

Prior to this change, there was a small window where the Nginx instance
used by feed-ingress could be active but without having loaded its
configuration. In this instance, the load balancer would be able to
reach it, but would receive a 404 response.
The solution is to only start Nginx after the first update has been
received and the configuration is ready - this means the load balancer
will only be able to reach it when it is suitably configured.
Fixes https://github.com/sky-uk/umc-core/issues/3586

Start Nginx only after first update is received

---

cmd/feed-dns/main.go
dns/dns_updater.go
dns/dns_updater_test.go

We found ourselves wanting to use `feed-dns` with a Route 53 zone that was already populated with existing records.  To facilitate this, we added a switch to allow `feed-dns` to only clean up records which alias existing load balancers that match feed's selection criteria.  While this does mean the cleanup could potentially leave records pointing to load balancers that have been deleted, we felt that this was a rare enough case to be a fair trade off for the ability to use the service with an existing zone.

Do not delete unassociated A records

---

.travis.yml
alb/alb.go
alb/alb_test.go
controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
controller/updater.go
dns/dns_updater.go
dns/dns_updater_test.go
elb/elb.go
elb/elb_test.go
nginx/nginx.go
nginx/nginx_test.go

The previous approach tried to order ingress by CreationTimestamp before
picking the most recent ingress.  This did not work because multiple
duplicate ingresses could be created at the same time.
This fix orders ingress entries by Namespace,Name,Host,Path and only
uses the first ingress 'Host/Path' encountered to dedupe.  Kuberentes
guarentees unique ingress for a given 'Namespace/Name' which will make
this deduping deterministic.
fixes: https://github.com/sky-uk/umc-core/issues/3793

Make deduping ingress entries deterministic.

---

CHANGELOG.md
alb/alb.go
alb/alb_test.go
cmd/feed-ingress/main.go
controller/controller.go
elb/elb.go
elb/elb_test.go

Avoid waiting deregistration time for alb/elb if there were no attached
instances, even if one was provided.

Avoid duplicate deregistration delay in both ALB/ELB

---

CHANGELOG.md
cmd/feed-ingress/main.go

when `elb-label-value` is provided

Fix skipping ELB updater creation

---

CHANGELOG.md
docker/ingress/Dockerfile
docker/ingress/logrotate.config
docker/ingress/logrotate.cron

Aggressively rotate access logs to reduce file system cache consumed by
the feed process. If the access log gets too large, it's possible for
kernel allocations to fail in high load situations.
We probably need a better off loading system for access logs here. For
now, this should help prevent all but the worse high load situations (in
which case you can simply disable access logs).

Aggressively rotate feed access logs

---

CHANGELOG.md
dns/dns_updater.go

Bump the entire record set log down to Debug, and add a new Info logging line with the number of current records.

Stop logging out the entire Route53 record set on update at Info

---

CHANGELOG.md
docker/ingress/build-nginx.sh
gorb/gorb.go
gorb/gorb_test.go

Use tee to update the arp configuration instead of echo, as the
redirection output is not done via sudo.
Also ensures the loopback interface check doesn't fail when no loopback
exists for the given VIP.
For #156

Fix wrong output redirection when managing loopback

---

CHANGELOG.md
controller/controller.go

Logging was introduced in https://github.com/sky-uk/feed/pull/157 and is very spammy.
I've left the actual log as presumably it is quite useful for testing but reduced the level to Debug.

Reduce logging in controller

---

nginx/fake_graceful_nginx.py

This is to change the path to python3.6 from using the absolute path to getting the dynamic path as it does not always live in /usr/bin/.

Changing the path to python3 for the fake graceful nginx script

---

CHANGELOG.md
cmd/feed-ingress/main.go
gorb/gorb.go
gorb/gorb_test.go
vendor/github.com/sethgrid/pester/LICENSE.md
vendor/github.com/sethgrid/pester/README.md
vendor/github.com/sethgrid/pester/pester.go
vendor/vendor.json

Changing the http client gorb uses to pester which allows us to define retry settings. [Pester](https://github.com/sethgrid/pester) uses the built-in golang http client and adds a wrapper allowing us more functionality when making basic http requests.
Adding two new feed ingress flags:
* gorb-http-client-timeout (default: 2s)
* gorb-http-client-max-retries (default: 3)

Gorb add HTTP retries using pester

---

.travis.yml

Need to skip cleanup, otherwise vendor gets nuked.

Fix feed releases

---

CHANGELOG.md
cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
docker/ingress/Dockerfile
docker/ingress/build-nginx.sh
examples/ingress.yml
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

The problem right now is there is no cap no connections per upstream. So if a service is slow, nginx will respond by actually increasing the number of connections - thus making things worse.

Nginx upstream max connections

---

CHANGELOG.md
cmd/feed-ingress/main.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

In some cases, this may need to be set to a value higher than the
default of 1 MiB, and is now configurable through the
`vhost-stats-shared-memory` flag. Default value is 1 MiB.

Configure memory allocated to vhost stats module

---

CHANGELOG.md
Gopkg.lock
Gopkg.toml
alb/alb.go
cmd/feed-dns/main.go
cmd/feed-ingress/main.go
controller/controller.go
dns/dns_updater.go
elb/elb.go
examples/feed-ingress-deployment-merlin.yml
gorb/gorb.go
gorb/gorb_test.go
k8s/client.go
k8s/watcher.go
merlin/merlin.go
merlin/merlin_test.go
nginx/nginx.go
nginx/nginx_metrics.go
util/cmd/cmd.go
util/metrics/prometheus.go

Also some small improvements:
* Expose the merlin request timeout, so it's easy to change if necessary
* Make deregistration more resilient, which could fail due to the long lived grpc connection getting killed. Instead, create and close connections on demand.

Attach to https in merlin

---

.gitignore
CHANGELOG.md
README.md
cmd/feed-ingress/main.go
controller/controller_test.go
controller/ingress_entry.go
k8s/status/status.go
k8s/status/status_test.go
merlin/status/status.go

Due to merlin using a cname for all DNS entries rather than a single ip
address, we need to supply both the internal and internet facing
hostnames as the ingress status. This will then allow external-dns to
create a cname from the ingress hostname to this relevant 'ingress'
hostname.

Adding internal and internet facing hostnames

---

CHANGELOG.md
k8s/status/status.go

This is to fix a bug where feed will quit the update ingress loop if
any status is 'unchanged' causing sporadic ingresses to be updated
or left unchanged.

Fix update ingress bug

---

CHANGELOG.md
k8s/status/status.go
k8s/status/status_test.go

This is to return back any errors recieved when trying to set an ingress
status rather than printing the names of the failed ingresses.
Closes #179

Expose status updater errors

---

nginx/nginx.tmpl

AND was being left behind as a literal and nginx fails to start. This commit will fix that

Remove AND operator in nginx template

---

controller/controller.go
controller/controller_test.go
elb/status/status.go
gorb/gorb.go
k8s/client.go
k8s/status/status.go
k8s/status/status_test.go
merlin/status/status.go
nginx/nginx.go
nginx/nginx_test.go
util/test/mocks.go

This fixes the issue where a duplicate ingress arises between a
path that has not been specified and a path of "/"
Connects https://github.com/sky-uk/core-infrastructure/issues/3686

Fix duplicate path when path is not specified

---

CHANGELOG.md
nginx/nginx.go
nginx/nginx_test.go

We start nginx after generating the config so we don't need to signal a
reload.  This was causing nginx to reload the config 5 minutes after
every startup which we know can be disruptive and is unnecessary.
Set the 'initial update' flag after starting nginx as this will ensure we
don't return true on the health endpoing before nginx is running.
Previously we set this flag just before starting nginx so it's
possible we were reporting healthy before the process was running.

Remove unnecessary config reload after start up

---

CHANGELOG.md

Ought to have been released as v1.13.0, as this change introduces new backwards-compatible functionality.

Fix most recent CHANGELOG entry

---

CHANGELOG.md
cmd/feed-ingress/main.go

The nginx default for max_conns is 0 so this changes our default to
to be the same.
Connects https://github.com/sky-uk/core-infrastructure/issues/3084

Change max_conns default from 1k to 0

---

nginx/nginx.go

This is to make sure that nginx is running even without any ingresses
created.
Required by https://github.com/sky-uk/core-infrastructure/issues/5172

Ensure nginx is running

---

CHANGELOG.md
go.mod
go.sum
nlb/nlb.go
nlb/nlb_test.go

- Attach to NLB using PrivateIP
> This is to attach to NLBs using the instance PrivateIP rather than the
InstanceID to get around
https://aws.amazon.com/premiumsupport/knowledge-center/target-connection-fails-load-balancer/
- Update CHANGELOG.md
Required by #3906

Attach to NLB using PrivateIP rather than InstanceID

---

CHANGELOG.md
alb/alb_metrics.go
alb/alb_test.go
dns/dns_metrics.go
elb/elb_metrics.go
elb/elb_test.go
go.mod
go.sum
gorb/gorb_metrics.go
gorb/gorb_test.go
nginx/nginx_metrics.go
nginx/nginx_test.go
nlb/nlb_metrics.go
nlb/nlb_test.go
util/cmd/cmd.go
util/metrics/prometheus.go

All metrics were being prefixed with `feed_dns_` since https://github.com/sky-uk/feed/commit/d3824d1b81b2baa211ff306ea50dfb08f9eb9fc5#diff-d0c5f4f4783e272c16b0fae89e62ce6f
Added missing assertion for metric `subsystem` to unit tests.

Fix incorrect metrics prefix

---

controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
nginx/fake_graceful_nginx.py
nginx/nginx.go
nginx/nginx_metrics.go
nginx/nginx_test.go

Don't start Nginx or reload the config if Update is called with 0
ingresses.  Instead, return an error and let the controller handle it.
This fixes an issue where the k8s client returns 0 ingresses during
startup and Nginx then returns http 404s for all ingresses.
Fix for the sorting of ingresses when filtering for unique entries.
This fixes an issue with flapping ingresses when the same path is
defined for different services under the same host. This flapping
was causing Nginx to reload frequently which is disruptive.  We now
include service and port in the sorting.
Add a metric for Nginx config reloads.
Required by https://github.com/sky-uk/core-infrastructure/issues/5657

Handle receiving 0 ingresses and prevent http 404s

---

.travis.yml
nlb/nlb.go
nlb/nlb_test.go

AWS NLB Targets are now registered to the Target Group using the correct
attachment type. Currently supports IP and Instance attachment types.
Required by sky-uk/core-infrastructure#3906

Support IP and Instance TargetGroup attachments

---

CHANGELOG.md
feed-ingress/cmd/common.go
feed-ingress/cmd/common_test.go
feed-ingress/cmd/root.go

Remove http binding by default, feed should be able to run with https only to avoid using an extra port.

Remove http binding by default

---

nginx/nginx.tmpl

The existing behavior is flawed in that it doesn't preserve the original
client's `Host` header as expected. Instead it uses nginx's own internal
host (which matches the server name), then it always appends the port.
To match the de facto convention of X-Forwarded-Host, we should simply
preserve the original client's `Host`.
An example of where this breaks is the docker registry:
1. Client tries to push to registry.com/my-repo/image:v1 via feed
ingress, hitting the blob upload endpoint
2. The registry gets `X-Forwarded-Host=registry.com:443`, so it
interprets itself as being `registry.com:443` rather than `registry.com`.
3. The registry then sends a `Location` header back with
`registry.com:443/my-repo/image` to push the layers
4. Client looks up credentials for `registry.com:443` which …

Fix X-Forwarded-Host to correctly forward client Host header

---

CHANGELOG.md
controller/ingress_entry.go
controller/ingress_entry_test.go

Each comma-separated entry should be either an IP address or a CIDR range. Ingresses where this isn't the case will be skipped, with an error message logged detailing the invalid entries.

Validate the sky.uk/allow annotation entries

---

controller/ingress_entry_test.go

To demonstrate that validation will correctly reject `sky.uk/allow` entries which contain newlines or whitespace.

Additional testcase in ingress_entry_test

---

CHANGELOG.md
controller/controller.go
controller/controller_test.go

Ensures that additional whitespace around ingress entries does not stop them being recognised as valid addresses or ranges.

Trim whitespace from sky.uk/allow entries

---

CHANGELOG.md
k8s/client.go
k8s/client_test.go

The update of an ingress status by a given feed pod F1 is a get-modify-set operation, where another feed instance F2 may potentially complete the set operation while F1 is still at the modify stage.
What this means is that when F1 comes to do its set operation, it will get back from the API server a "409 Conflict" response, indicating that someone else has modified the resource after F1 fetched it.
This change makes the update routine a little more resilient. If a feed pod receives a conflict response back when it attempts to update the status, it will perform a second get operation, and compare the status on the returned object with the status it wanted to set. If these are equal, it will not return any error.
In the case where the status on the returned object is not equal to the value …

Account for concurrent status updates

---

CHANGELOG.md
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Nginx included in the feed docker image doesn' t produce "404 Not Found" for servers which ingresses don't contain an ingress for the root path. Instead, the default Nginx index page is used as the response. 
To stop this behaviour, for all servers without the root ingress, the additional location for the root path will be added to locations generated from ingresses. This location will return "404 Not Found".
Required by sky-uk/core-infrastructure#6782 (https://github.com/sky-uk/core-infrastructure/issues/6782#issuecomment-619034128)

Generate the root path location for servers without the root ingress

---

CHANGELOG.md
nlb/nlb.go
nlb/nlb_test.go

This changes from one call per load balancer to one call to get the
information for available target groups. This is needed so that the
number of API calls is reduced to avoid becoming rate limited.
It now also returns an error if the target group information can't be
retrieved, instead of ignoring the failure, and setting TargetGroups to
nil. This caused feed to mark itself as initialised, when it wasn't, and
it never recovered. Now that it fails, it should retry to register in
the next Update cycle.

Reduce number of DescribeTargetGroups calls on NLB

---

CHANGELOG.md
nginx/nginx_metrics.go
nginx/nginx_test.go

Misconfigured ingress resources have the ability to create invalid
VTS entries. These are long-lived and are not rectified againt the
running nginx config.
Because of this, it is possible that the metrics exported by feed
can flip between the valid and invalid VTS data causing erroneous
metrics to be exported.
This adds an extra filter to ensure that metrics are not generated
for misconfigured ingress resources.
Required by https://github.com/sky-uk/core-infrastructure/issues/7091

Skip misconfigured vts entries

---

controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
go.mod
go.sum
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

- Support setting `keepalive_requests` and `keepalive_timeout` for nginx upstream module
- Support annotations on ingress to be able to set the values in nginx config for each upstream

Support latest backend config for nginx upstream module

---

CHANGELOG.md
README.md
feed-ingress/cmd/root.go
go.mod
go.sum
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

- Specify the name of the header to use by the real ip module to derive the ip of the client to apply allow/deny rule.

Specify the name of the header to use for deriving client ip

---

CHANGELOG.md
README.md
controller/controller.go
controller/controller_test.go
feed-ingress/cmd/common.go
feed-ingress/cmd/root.go
k8s/client.go
k8s/client_test.go
util/test/mocks.go

- Remove flag `--ingress-controller-namespace-selector`
- Add flag `--ingress-controller-namespace-selectors` - which can accept comma separated or repeated inputs
- Add flag `--match-all-namespace-selectors` - for how to match the above provided labels

Add support for multiple namespace selectors

---

CHANGELOG.md
Makefile
docker/ingress/Dockerfile
nlb/nlb.go
nlb/nlb_test.go
trivy-ignore-file.txt

- Feed instance can attach to multiple target groups belonging to the load balancer having a tag matching the value in the flag `ingress-class`. The fix is for feed instance to wait for the drain duration even if the de-register call succeeds to at least one of those target groups.
closes https://github.com/sky-uk/feed/issues/233

Fix bug during feed shutdown

---

controller/ingress_entry.go
controller/ingress_entry_test.go

k8s does not validate path entries that are part of ingresses, at least
not to the level of stringency that feed expects.  this can lead in some
cases to invalid nginx config being generated due to insufficient
santitzation.  the new approach is to reject paths which donʼt conform
strictly to the rfc 3986 definition of a path.
thanks @jsws for finding this bug

validate paths passed to feed

---

alb/alb.go
alb/alb_test.go
controller/controller.go
controller/controller_test.go
controller/updater.go
dns/dns_updater.go
elb/elb.go
elb/elb_test.go
elb/elbstatus/status.go
external/status.go
gorb/gorb.go
merlin/merlin.go
merlin/status/status.go
nginx/nginx.go
nlb/nlb.go
nlb/nlb_test.go
nlb/nlbstatus/status.go
util/cmd/cmd.go

The readiness endpoint calls down to a readiness method on the
controller, just as the healthcheck endpoint does.  The readiness
endpoint is implemented as a loop over all the controllerʼs owned
objects to poll them for readiness.
Most object types implement readiness by just returning the result of
their healthcheck.  The ALB and ELB types keep track of whether they have been registered with AWS, and return that status as their readiness.  The the NLB object type is where interesting things happen.  The AWS docs
call out a situation where it can take “a few minutes” for
healthchecking of an instance registered with a target group to begin.
During this interval, k8s should consider that replica “healthy” (itʼs
registered with the NLB successfully), but not “ready” (itʼs not
receiving …

Add a readiness endpoint to feed.

---

nginx/nginx.tmpl

When a large number of ingresses are created, we get into a situation where the line length on the ingresses comment exceeds the maximum allowed for an nginx config line and this stops nginx from starting up.

Truncate comment to fit under the line limit for nginx config
