.gitignore
.travis.yml
Makefile
README.md
cmd/feed-ingress/main.go
docker/.dockerignore
docker/.gitignore
docker/Dockerfile
ingress/controller.go
ingress/controller_test.go
ingress/fake_nginx.sh
ingress/lb_entry.go
ingress/lb_entry_test.go
ingress/loadbalancer.go
ingress/loadbalancer_test.go
ingress/nginx.go
ingress/nginx.tmpl
test-ingress.yml

Depends on #4
I went with Alpine to keep the image small.
Alternative implementation would have the nginx in a different container but this way this image is self contained.

Add nginx management and docker container

---

Makefile
cmd/feed-ingress/main.go
ingress/controller.go
ingress/controller_test.go
ingress/fake_failing_nginx.sh
ingress/fake_graceful_nginx.py
ingress/fake_nginx.sh
ingress/loadbalancer.go
ingress/nginx.go
ingress/nginx_test.go

Two separate commits - please don't squash them.
First one fixes loadbalancer to terminate nginx gracefully.
Second fixes controller to shutdown gracefully.

Graceful termination of nginx

---

.travis.yml

Before it was including PRs that were being tested against master.

Only release on a master build

---

cmd/feed-ingress/main.go

Log to stdout by default

---

.travis.yml
Makefile

Fail the build if files are not formatted.
Also organized the Makefile to make it a bit clearer the various
targets.

Check formatting in travis

---

cmd/feed-ingress/main.go
ingress/controller.go
ingress/controller_test.go

Needed so nginx can resolve services against skydns without the built in
resolv.conf that normally includes search domains.

Add search domain for backend services

---

Dockerfile

For debugging issues. Also do an update of the base system to fix any
vulnerabilities.

Add dig and curl to docker image

---

cmd/feed-ingress/main.go
ingress/api/loadbalancer.go
ingress/controller.go
ingress/controller_test.go
ingress/nginx/nginx.go
ingress/nginx/nginx_test.go
k8s/client.go
k8s/client_test.go
k8s/watcher.go
util/safe.go

Also change the `Healthy() bool` methods to `Health() error` so we can more easily debug issues in running controllers.

Unhealthy if controller is not watching

---

cmd/feed-ingress/main.go

Since we'll need this port regardless of what the implementation is.
It's used by frontends to determine health of ingress.

Rename 'nginx-status-port' to 'ingress-status-port'

---

cmd/feed-ingress/main.go
ingress/nginx/nginx.go
ingress/nginx/nginx.tmpl

Remove nginx resolver flag

---

Dockerfile

Update nginx to 1.10.1

---

elb/elb.go
elb/elb_test.go

Doh, all of the other demo comments were actually in umc-platform so should have just snook this in the last one

Failed to start if expected frontends not matched

---

cmd/feed-ingress/main.go
elb/elb.go
elb/elb_test.go

So it's clearer how they will be used by ingress.

Make the ELB flags specific to ELBs

---

elb/elb.go
elb/elb_test.go

This information is needed when creating A records in route53 that are
using the TargetAlias functionality.
Needed For: https://github.com/sky-uk/umc-core/issues/772

Store frontend CanonicalHostedZoneNameIDs

---

cmd/feed-dns/main.go
cmd/feed-ingress/main.go
k8s/client.go
k8s/client_test.go
util/cmd/k8s_client.go

Kubernetes supports private/public keys with client TLS certificates
over token authentication.

Support kubernetes client certificates

---

cmd/feed-ingress/main.go
util/cmd/cmd.go

New flag `-pushgateway` which if provided pushes metrics to a prometheus
pushgateway.

Add pushgateway support

---

dns/r53/client.go
dns/r53/client_test.go
elb/elb.go
util/slices.go
util/slices_test.go

This is based off the #66 branch so do that one first and I will rebase this one

Dns large record updates (Depends on #66)

---

README.md

Starting to add more detail to the readme so someone external to our team has a chance of understanding that this project does :)

Update readme for feed-dns

---

cmd/feed-dns/main.go
cmd/feed-ingress/main.go
dns/dns_metrics.go
dns/dns_updater.go
elb/elb.go
nginx/nginx.go
nginx/nginx_metrics.go
util/cmd/cmd.go
util/cmd/keyvalue.go
util/metrics/prometheus.go

So we can label things like k8s cluster and version.

Add ability to specify arbitrary prometheus labels

---

k8s/client_test.go
k8s/watcher.go

Watchers have a grace period before they are considered unhealthy.

Don't go unhealthy on long poll disconnects

---

dns/dns_metrics.go
dns/dns_updater_test.go
elb/elb.go
elb/elb_metrics.go
elb/elb_test.go
nginx/nginx_metrics.go
nginx/nginx_test.go
util/cmd/cmd.go
util/metrics/prometheus.go

As detected by the race detector (see
https://travis-ci.org/sky-uk/feed/builds/143821052).

Fix race conditions in metrics

---

cmd/feed-ingress/main.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Add a flag `-ingress-strip-path` to allow enabling it.

Disable ingress path stripping by default

---

cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
ingress.yml
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

I single timeout is not flexible enough as different services will need
different timeouts.

Allow per ingress backend timeout in nginx

---

controller/controller.go
controller/ingress_entry.go

So we can figure out which ingresses are invalid.

Improve the invalid entry logs

---

cmd/feed-ingress/main.go
examples/pod.yml
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

https://github.com/sky-uk/umc-core/issues/2121

Introduce iso8601 timestamp and http headers in access logs

---

nginx/nginx.go
nginx/nginx_test.go

Fix for defect in https://github.com/sky-uk/umc-core/issues/2121

Fix log header format to replace dashes with underscores

---

.travis.yml
alb/alb_test.go
cmd/feed-ingress/main.go
controller/controller.go
controller/controller_test.go
controller/ingress_entry.go
dns/dns_updater.go
elb/elb_test.go
nginx/blocking_nginx.sh
nginx/fake_graceful_nginx.py
nginx/fake_nginx.sh
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

- Names now reflect the backend service
- Common upstreams are now shared rather than being duplicated

Improve upstream names and organisation

---

k8s/client.go

One second is far too conservative. The main point of this is to hide
rapid repeat updates, such as when the store produces an update per
existing entry at startup. It's up to the updaters, such as nginx, to
use more conservative times if they need it.

Reduce buffered watcher duration

---

nginx/nginx.go
nginx/nginx_metrics.go
nginx/nginx_test.go

* Scrape all metrics from VTS's /status/format/json page
* Add per ingress and per endpoint request counts
* Add per ingress and per endpoint byte counts

Expand prometheus metrics

---

README.md

I realized that I hadn't updated the README.md with my previous changes.  Sorry about that!

Update README.md to reflect feed-dns startup changes

---

CHANGELOG.md
README.md
cmd/feed-ingress/main.go
nginx/nginx.go
nginx/nginx.tmpl
nginx/nginx_test.go

Connects https://github.com/sky-uk/feed/issues/186

Support handling of large client requests

---

dns/r53/client.go
nginx/nginx.go

Use Codelingo to automatically fix function comments following the
[effective go guidelines](https://golang.org/doc/effective_go.html#commentary) in [CONTRIBUTING.md](CONTRIBUTING.md).
This patch was generated by running the Codelingo Rewrite Flow over the "[comment-first-word-as-subject](https://github.com/codelingo/codelingo/blob/master/tenets/codelingo/effective-go/comment-first-word-as-subject/codelingo.yaml)" Tenet. Note: the same Tenet can be used to automate PR reviews and generate guideline docs. Install CodeLingo: https://github.com/apps/codelingo

Patch comments according to best practices in CONTRIBUTING.md

---

CHANGELOG.md
Gopkg.lock
controller/controller.go
controller/controller_test.go

Ingress can be created without Http and path, feed should skipped ingress definition withouth host definition.

Skip ingress when http and/or path are not defined

---

CHANGELOG.md

Required by https://github.com/sky-uk/core-infrastructure/issues/5657

Update changelog for v2.2.3

---

README.md

Stating that it may take up to 2 minutes for Feed pods to register with an NLB.

Additional information in README.md

---

go.sum
nginx/nginx.go

this to ensure to exit when nginx reload fails due to master process being killed
for https://github.com/sky-uk/core-networking/issues/3161

exit-when-nginx-reload-sig-failed
